### ISSUE TITLE
Should SpiceMix be used before or after integration with scRNA-seq and visium

### ISSUE THREAD

**Issue by LinearParadox** [ma-compbio/SpiceMix#4]
Hi all,

I have some samples with spatial experiments that I would like to integrate with scRNA seq experiments. I was wondering whether it would be better to run SpiceMix on the data before it is integrated, or integrate the data first and then run SpiceMix.

**Comment by tianmingzhou** [comment]
Hi,

Thanks for your interest in SpiceMix!

We believe either way is feasible. The latest version of SpiceMix is much faster, so we suggest trying both and seeing which one works better for your scenario.
