### ISSUE TITLE
GPU/CPU use

### ISSUE THREAD

**Issue by heilandd** [ma-compbio/SpiceMix#5]
Hallo, 

the current version is only working using the GPU based on the pin_memory() in the load_dataset function of the model.py.

To use it with the cpu, the following lines need to be removed from the model.py

87 #torch.tensor(Y, **self.context_Y).pin_memory()
88 #if self.context_Y.get('device', 'cpu') == 'cpu' else

correct if I am wrong but shouldn't it be :

self.Ys = [
            if self.context_Y.get('device', 'cpu') == 'cpu':
                torch.tensor(Y, **self.context_Y)
            else:
                torch.tensor(Y, **self.context_Y).pin_memory()
			for Y in self.Ys
		] 

Best, Henrik

**Comment by tianmingzhou** [comment]
Hi Henrik,

Thank you for bringing this issue to our attention and for your interest in SpiceMix. We've made updates to the `model.py` file to ensure it works regardless of whether a GPU is available.

However, please note that your proposed modification may cause an error when the `context_Y['device']` is set to a GPU device, as PyTorch does not support the use of `pin_memory()` on GPU tensors.

Best,
Tianming
